# Generated by Django 3.1.4 on 2021-01-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_installers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pkg_name', models.TextField(blank=True, null=True)),
                ('pkg_url', models.TextField(blank=True, null=True)),
                ('pkg_summary', models.TextField(blank=True, null=True)),
                ('installer_name', models.TextField(blank=True, null=True)),
                ('installer_url', models.TextField(blank=True, null=True)),
                ('anaconda_ver', models.TextField(blank=True, null=True)),
                ('python_ver', models.TextField(blank=True, null=True)),
                ('pkg_ver', models.TextField(blank=True, null=True)),
                ('pkg_included', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'packages',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Package_Installer',
        ),
    ]
