# Generated by Django 3.1.4 on 2021-01-07 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_installers', '0002_auto_20210106_0517'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Packages',
            new_name='Package',
        ),
    ]
